# Generated by Django 2.1.5 on 2020-05-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='检查结果')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
            ],
        ),
        migrations.CreateModel(
            name='DBConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('desc', models.CharField(max_length=256)),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='created datetime')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='updated datetime')),
            ],
        ),
        migrations.AddField(
            model_name='checktask',
            name='db',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='ops.DBConf', verbose_name='目标数据库'),
        ),
        migrations.AddField(
            model_name='checktask',
            name='sentence',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='ops.SentenceTemplate', verbose_name='语句'),
        ),
    ]
