# Generated by Django 2.1.5 on 2020-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconf',
            name='dbname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='db名称'),
        ),
    ]
