# Generated by Django 2.1.5 on 2020-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_dbconf_dbname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconf',
            name='port',
            field=models.IntegerField(default=1433, verbose_name='端口'),
        ),
    ]
