# Generated by Django 2.1.5 on 2020-06-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_dbconf_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checktask',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='检查结果'),
        ),
        migrations.AlterField(
            model_name='dbconf',
            name='port',
            field=models.CharField(default='1433', max_length=128, verbose_name='端口'),
        ),
    ]
