# Generated by Django 2.1.5 on 2020-06-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_auto_20200625_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.TextField(verbose_name='结果')),
            ],
        ),
    ]
