# Generated by Django 2.1.5 on 2020-07-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_inspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbconf',
            name='dbname',
        ),
    ]
